################################
### get all user
GET http://localhost:3000/bomaylaadmin/getall
Content-Type: application/json

################################
###register
POST http://localhost:3000/bomaylaadmin/register
Content-Type: application/json

{
    "fullName":"prevlife2",
    "phone":"2",
    "password":"1234",
    "role":"SHIPPER"
}

################################
###Login
POST http://localhost:3000/bomaylaadmin/login 
Content-Type: application/json

{
    "phone":"2",
    "password":"1234"
}

################################
###update
Post http://localhost:3000/bomaylaadmin/edit/2

{
    "fullName":"Previous Life", 
    "email":"",
    "dateOfBirth":"",
    "province":"",
    "district":"",
    "ward":"",
    "apartmentAddress":"",
    "profilePicture":"",
    "role":"",
    "password":"",
}

################################
###update
Post http://localhost:3001/vouchers/update/61acd9ee397fa9f04e1cdee7
Content-Type: application/json

{
    "_id": "61acd9ee397fa9f04e1cdee7",
    "name": "Voucher discount 10% price",
    "code": "ELAP10PERCENT",
    "image": "voucher.jpg",
    "type": "percent",
    "value": 0.1,
    "limit": 10,
    "start": "5-12-2021",
    "end": "15-1-2022",
    "description": "This voucher will discount your order 10%"

}

